name: manga-translator
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip:
      - huggingface_hub
      - torchmetrics
      - datasets
      - Pillow
      - albumentations
      - numpy
      - ultralytics
      - onnx
      - onnxruntime
      - dotenv
      - opencv-python-headless
      - transformers
      - torch
      - torchvision
